name: 'k6registry setup'
description: 'setups k6 registry'
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: "1.24.x"

    - name: Setup xk6
      uses: grafana/setup-xk6@97b842b765bd3fea56db7195e98c5f61cab8fe46 # v1.1.1
      with:
        xk6-version: 1.2.3

    - name: Setup xk6 lint dependencies
      shell: bash
      run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
          go install github.com/securego/gosec/v2/cmd/gosec@v2.22.10

    - name: Setup k6registry
      shell: bash
      run: >
          go install github.com/grafana/k6registry/cmd/k6registry@v0.5.1
